//##header J2SE15
/*
 *******************************************************************************
 *   Copyright (C) 2001-2007, International Business Machines
 *   Corporation and others.  All Rights Reserved.
 *******************************************************************************
 */

// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20101125_01     
// 12/13/10 10:46 AM    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
namespace IBM.ICU.Charset
{

    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.IO;
    using System.Runtime.CompilerServices;

    /// <summary>
    /// Top level test used to run all other tests as a batch.
    /// </summary>
    ///
    public class TestAll2 : TestFmwk.TestGroup
    {

        public static void Main(String[] args)
        {
            new TestAll().Run(args);
        }

        public TestAll2()
            : base(null, new String[]{"com.ibm.icu.dev.test.bidi.TestCharFromDirProp","com.ibm.icu.dev.test.bidi.TestBidi","com.ibm.icu.dev.test.bidi.TestInverse","com.ibm.icu.dev.test.bidi.TestReorder","com.ibm.icu.dev.test.bidi.TestFailureRecovery","com.ibm.icu.dev.test.bidi.TestMultipleParagraphs","com.ibm.icu.dev.test.bidi.TestReorderingMode","com.ibm.icu.dev.test.bidi.TestReorderRunsOnly","com.ibm.icu.dev.test.bidi.TestStreaming","com.ibm.icu.dev.test.bidi.TestClassOverride",// #if defined(FOUNDATION10) || defined(J2SE13)
	                // #else
	                "com.ibm.icu.dev.test.bidi.TestCompatibility"}, "Bidi tests")
        {
        }

        public const String CLASS_TARGET_NAME = "Bidi";
    }
}
