// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20101125_01     
// 12/13/10 10:46 AM    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 /// <summary>
/// Copyright (C) 2005, International Business Machines Corporation and         
/// others. All Rights Reserved.                                                
/// </summary>
///
namespace IBM.ICU.Charset {
	
	using System;
	using System.Collections;
	using System.Collections.Generic;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	
	public sealed class TestLogWriter : TextWriter {
	    private TestLog log;
	
	    private int level;
	
	    private bool closed;
	
	    public TestLogWriter(TestLog log_0, int level_1) {
	        this.log = log_0;
	        this.level = level_1;
	    }
	
	    public override void Write(char[] cbuf, int off, int len) {
	        Write(new String(cbuf, off, len));
	    }
	
	    public override void Write(String str) {
	        if (closed) {
	            throw new IOException("stream closed");
	        }
	        if ("\r\n".IndexOf(str) != -1) {
	            log.Msg("", level, level == IBM.ICU.Charset.TestLog_Constants.ERR, true);
	        } else {
	            log.Msg(str, level, level == IBM.ICU.Charset.TestLog_Constants.ERR, false);
	        }
	    }
	
	    public override void Flush() {
	    }
	
	    public override void Close() {
	        closed = true;
	    }

        public override System.Text.Encoding Encoding
        {
            get { throw new NotImplementedException(); }
        }
    }
}
