// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20101125_01     
// 12/2/10 11:47 AM    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace IBM.ICU.Impl {
	
	using System;
	using System.Collections;
	using System.Collections.Generic;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	public class UCharacterNameChoice_Constants {
	
	    public const int UNICODE_CHAR_NAME = 0;
	    public const int UNICODE_10_CHAR_NAME = 1;
	    public const int EXTENDED_CHAR_NAME = 2;
	    public const int CHAR_NAME_CHOICE_COUNT = 3;
	    public const int ISO_COMMENT_ = CHAR_NAME_CHOICE_COUNT; 
	}
}
